FROM python:3-onbuild
COPY . /usr/src/app
CMD ["python", "client.py"]
EXPOSE 8765

#FROM python:3.6
#COPY . /usr/src/app
#RUN pip install --upgrade pip
#COPY . /app/client/
#WORKDIR /app/test-client/
##RUN pip install scikit-learn
#RUN pip install -r /app/client/requirements.txt
#EXPOSE 8765
