version: '3'

services:
  redis_service:
    container_name: redis_service
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always

  prediction_server:
      build: ./prediction_server
      volumes:
        - ./prediction_server:/usr/src/app
      ports:
        - 5000:5000

  worker:
    image: engineeringthesis_prediction_server:latest
    command: rq worker --url redis://redis_service:6379 queue_update_model
    depends_on:
      - redis_service
    links:
      - redis_service

  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app
    ports:
      - 8765:8765

  evaluation_server:
    build: ./evaluation_server
    volumes:
      - ./evaluation_server:/usr/src/app
    ports:
      - 8766:8766

  cassandra:
    image: cassandra:2.1.20
    volumes:
      - "./cassandra-init.sh:/cassandra-init.sh"
    command: "sh /cassandra-init.sh"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]

