version: '3'

services:
  redis_service:
    container_name: redis_service
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always

#  worker:
#    container_name: worker
#    build: .
#    volumes:
#      - ./prediction_server:/usr/src/app
#    command: celery worker -B -l info -A tasks
#    depends_on:
#      - redis_service
#      - prediction_server
#    links:
#      - redis_service

  prediction_server:
      build: ./prediction_server
      volumes:
        - ./prediction_server:/usr/src/app
      ports:
        - 5000:5000

  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app
    ports:
      - 8765:8765