version: '3'

services:
  redis_service:
    container_name: redis_service
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always

  prediction_server:
      build: ./prediction_server
      volumes:
        - ./prediction_server:/usr/src/app
      ports:
        - 5000:5000

  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app
    ports:
      - 8765:8765