FROM cassandra:latest
#COPY . /usr/src/app
#
#RUN apt-get -y update \
#    && apt-get -y upgrade \
#    && apt-get install -y python3-pip python3-dev \
#    && pip3 install -r /usr/src/app/requirements.txt

#FROM engineering_thesis_cassandra_api
#CMD ["python3", "/usr/src/app/clear_cassandra.py"]